### ISSUE TITLE
[name]-[song]_DONOTEDIT-OR-EXECUTE.lua what does this mean?

### ISSUE THREAD

**Issue by MLGNote** [accountrev/funkychart#25]
so im trying to convert my .osu chart ot .lua and it works just fine, but when i do, at the end it says "DONOTEDIT-OR-EXECUTE" and executing the .lua script doesn't work. i tried a custom chart of Sporting from vs matt mod and i had this problem, so as a test i try target practice from the same mod and it happens again.
something else i noticed, this doesnt happen in [this video](https://www.youtube.com/watch?v=juM02bEOqPo&t=240s) for some reason. to comapre, the .lua name is (Account!!!_FREEDOM DiVE_1647194828.763302.lua) while mine is (MLGNote-Sporting_DONOTEDIT-OR-EXECUTE.lua). is there something that changed? was something patched? if it helps to know im using krnl since i dont have the money for synapse just yet. thanks for the help in advance!

**Comment by accountrev** [comment]
Hey, thanks for asking.
There were many people that were having problems with FunkyChart because they were actually opening the chart file and executing that instead of the GUI and doing it through there. That's why I put "DONOTEDIT-OR-EXECUTE" just incase if someone believes that have to execute the chart into the game.
As for the video, this is an older version of the script (v1.0) so when you converted a file in that version, it never included that part of the filename. The tutorial should work the same way still, but I will be making an updated version when I have the time.
