### ISSUE TITLE
Can't use the chart and have this error in the converter

### ISSUE THREAD

**Issue by reljw** [accountrev/funkychart#26]
![image](https://user-images.githubusercontent.com/86134952/163801060-0aa4b094-8326-443e-8977-4bce1675b4ea.png)
![image](https://user-images.githubusercontent.com/86134952/163801166-161e455c-3e98-45d5-8e7b-5112e3b4c173.png)

**Comment by reljw** [comment]
b1ThtT5u5SRfZsi9:240:

**Comment by accountrev** [comment]
This error happens when the osu file you are trying to convert is an not a normal chart, meaning that the beatmap wasn't properly created inside of osu!'s beatmap editor (either the beatmap was tampered with or the beatmap was generated using another tool for a different game).
I had many instances of players converting Friday Night Funkin' maps to osu, then converting that map again using FunkyChart. The error just means that one of the notes aren't properly located in the right column.
This will be fixed in the future ahead, but for now can you send me a link to the file you are converting? If it's on the osu! website, just send a link to that instead. Thanks!
